name: mnist-uncertainty
channels: !!python/tuple
- conda-forge
- defaults
dependencies:
- conda-forge::numpy=1.12.1=py35_blas_openblas_200
- conda-forge::pip=9.0.1=py35_0
- conda-forge::python=3.5.3=1
- conda-forge::matplotlib=2.0.0=np112py35_3
- conda-forge::notebook=5.0.0=py35_0
- conda-forge::seaborn=0.7.1=py35_0
- conda-forge::scikit-learn=0.18.1=np112py35_blas_openblas_200
- conda-forge::scipy=0.19.0=np112py35_blas_openblas_200
- conda-forge::theano=0.9.0=py35_0
- pip:
    - tensorflow==1.1
    - keras==2.0.3
    - edward==1.3.1
